// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSkw9HQNwmDf6pK23PRPacsQGiyf58zqI',
    appId: '1:96889276332:web:13112895a9cd5972d45c09',
    messagingSenderId: '96889276332',
    projectId: 'inventory-app-a36c6',
    authDomain: 'inventory-app-a36c6.firebaseapp.com',
    storageBucket: 'inventory-app-a36c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpCoU-SkoEq554YzsxoT0ulEn26NAmUY',
    appId: '1:96889276332:android:7ebbf928ef44e0d7d45c09',
    messagingSenderId: '96889276332',
    projectId: 'inventory-app-a36c6',
    storageBucket: 'inventory-app-a36c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw5rp4ZkItrv2xV3sh7WSDppZiUDDHoc0',
    appId: '1:96889276332:ios:57ea9189dc64b999d45c09',
    messagingSenderId: '96889276332',
    projectId: 'inventory-app-a36c6',
    storageBucket: 'inventory-app-a36c6.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw5rp4ZkItrv2xV3sh7WSDppZiUDDHoc0',
    appId: '1:96889276332:ios:57ea9189dc64b999d45c09',
    messagingSenderId: '96889276332',
    projectId: 'inventory-app-a36c6',
    storageBucket: 'inventory-app-a36c6.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSkw9HQNwmDf6pK23PRPacsQGiyf58zqI',
    appId: '1:96889276332:web:cfe0e1ed8a38b1cbd45c09',
    messagingSenderId: '96889276332',
    projectId: 'inventory-app-a36c6',
    authDomain: 'inventory-app-a36c6.firebaseapp.com',
    storageBucket: 'inventory-app-a36c6.firebasestorage.app',
  );
}
